### ISSUE TITLE
Tooltip does not align 

### ISSUE THREAD

**Issue by jkarimi91** [wa0x6e/cal-heatmap#154] opened 2015-06-26 18:52 UTC
I am trying to center the heatmap, however, the tooltip becomes misaligned in the process.
[code on jsfiddle](http://jsfiddle.net/jkarimi91/73b6djqa/1/)

**Comment by kamisama** [comment] 2015-06-26 18:57
Jsfiddle not working ?

**Comment by jkarimi91** [comment] 2015-06-26 18:59
sorry I posted the wrong jsfiddle link, I corrected the link; take a look, the tooltip does not realign

**Comment by jkarimi91** [comment] 2015-07-14 19:18
@kamisama  any updates?

**Comment by nahankid** [comment] 2015-10-29 03:39
Tooltips are not aligning even with the latest release

**Comment by lops** [comment] 2015-11-17 01:44
for what it's worth, this worked for me (sorry if its a bit hack-y)...
added these two lines after 899.
var offsetWidth = domainNode.parentNode.parentNode.parentNode.parentNode.offsetWidth - domainNode.parentNode.parentNode.parentNode.offsetWidth;
tooltipPositionX = tooltipPositionX + offsetWidth / 2;

**Comment by rcaloras** [comment] 2016-01-16 09:00
+1 would love a fix.

**Comment by vlux** [comment] 2016-01-22 08:44
Hey Guys
I encountered this bug as u.
My range is 7. When I set the `width:900px` for `#cal-heatmap` as [This Issue] (https://github.com/wa0x6e/cal-heatmap/issues/79) mentioned. The tooltip align as normal. However the svg was drawn beyong the `#cal-heatmap` which is only 900px width.

So I use the code below to adjust the svg position. 
```
    var div_width = $("the_parent_div").width()
    var svg_width = $(".cal-heatmap-container").width()
    var left = (div_width - svg_width) / div_width 
    left = Math.floor(left * 50) + '%'
    $("#cal-heatmap").css("margin-left",left)
   // if u set the #cal-heatmap to svg, the tooltip will fly away again :)
```
U can put this code in the 'document.ready()' or 'window.onload' in case the jquery can not find the '.cal-heatmap-container'

Hope u can fix ur bug :)
@jkarimi91 @rcaloras @wa0x6e @nahankid

**Comment by JoshKeegan** [comment] 2016-05-16 14:01
:+1:

**Comment by scottharvey** [comment] 2018-09-13 09:54
I hit this same issue today, I updated the [jsfiddle](http://jsfiddle.net/jr0837v6/4/) to show that the issue is still present in version 3.6.2.

Any update on this would be great, thanks for the awesome library 😄

**Comment by scottharvey** [comment] 2020-03-31 13:11
I added this to calculate the x offset correctly when the heatmap is centered.

`tooltipPositionX += parseInt(domainNode.parentNode.parentNode.getBoundingClientRect().x, 10) - parseInt(self.root[0][0].parentNode.getBoundingClientRect().x, 10);`

I put that on about line 900 after this

`tooltipPositionY += parseInt(domainNode.parentNode.getAttribute("y"), 10);`

I can create a PR if the maintainer requests one but this library doesn't seem like it's active.

**Comment by wa0x6e** [comment] 2022-11-19 13:49
Fixed in v4, now using popperjs

**Closed by wa0x6e** 2022-11-19 13:49 UTC
Labels: bug
