### ISSUE TITLE
Some weeks info is missing

### ISSUE THREAD

**Issue by roufs42** [wa0x6e/cal-heatmap#222] opened 2016-11-04 10:43 UTC
When we put Month as Domain and Week as SubDomain the weeks which are staring 1st of the month as Monday are missing can u pls check it out once

**Comment by ellesborough** [comment] 2018-01-15 16:24
I have seen this too in Month/Week mode.  
Some weeks appear out of order, some weeks over-write other weeks, some weeks are duplicated in more than one month.

**Comment by wa0x6e** [comment] 2018-01-16 08:21
Which setting are you using to reproduce this issue ?

**Comment by ellesborough** [comment] 2018-01-16 09:59
In the example below, the 200 value for 2017-12-01 doesn’t appear at all, the hover tooltip for the last week of November says “100 items in November Week #47” and the first week of December is “400 items in December Week #48”

 

Also there is an extra week on the end of January that says “December Week #52”

 

Setting “weekStartOnMonday” changes it such that an extra cell “October Week #44” appears between  Week #48 and Week #49

 

“domainDynamicDimension” can also have an effect too.

 

I’ve created a JSFiddle for you to see it in action: https://jsfiddle.net/ellesborough/ufha1wga/

 

 

Peter

 

 



 

var cal = new CalHeatMap();

cal.init({

    data: {

                [new Date("2017-11-23").getTime()/1000] : 50,

                [new Date("2017-11-30").getTime()/1000] : 100,

                [new Date("2017-12-01").getTime()/1000] : 200,

                [new Date("2017-12-05").getTime()/1000] : 400

              }, 

        domain: 'month',                        

        subDomain :"week",      

        domainDynamicDimension : false,

        weekStartOnMonday :  false,   

        start : new Date("2017-11-16"),

        range : 3,                

});

**Comment by navixia** [comment] 2019-10-08 09:02
Hello,

I have exactly the same issue. Any update on this one ?

**Comment by wa0x6e** [comment] 2022-12-01 20:06
Weeks positioning issues is fixed in master.
Duplicate issue is still pending

**Comment by wa0x6e** [comment] 2023-02-21 14:27
Duplicate issue is now fixed.

Missing data issue still pending, it's due to month domain clamping the dataset to the domain scope, even though the week subdomain can span over 2 months.

**Closed** 2023-02-23 21:37 UTC
Labels: bug
