### ISSUE TITLE
Hovering over a cell cuts off the border on the edges

### ISSUE THREAD

**Issue by WilliamStam** [wa0x6e/cal-heatmap#108] opened 2014-09-30 08:24 UTC
i noticed this in my project. when you hover over a cell on the edge it sometimes "cuts off" the border. it does the same on the docs eg's

i really doubt this is intended behaviour.

![image](https://cloud.githubusercontent.com/assets/182800/4455131/11b9eb86-487b-11e4-8dfb-894fbf8d285d.png)

my project screenshot is in firefox (latest) and the docs screenshot was done in chrome latest.

**Comment by kamisama** [comment] 2015-01-19 23:24
Are you using twitter bootstrap ?

From my tests, there's a cut-off on three sides when using bootstrap, and it happens onlt on the right side when no bootstrap.

There is some overflow:hidden issue. If you did not enable domain navigation, you could put a `overflow:visible;` to all svg elements to temporary fix the issue.

**Comment by WilliamStam** [comment] 2015-01-20 05:20
yips im using bootstrap. I presume the docs also uses bs? (on mobile now cant check)

**Comment by kamisama** [comment] 2015-01-24 04:28
yes, the doc does use tw bootstrap, and there's a rule inside putting a overflow:hidden to all non root svg.

**Comment by kamisama** [comment] 2015-01-24 04:58
In the mean time, there's a dirty fix in #118

**Comment by outaTiME** [comment] 2016-03-25 20:42
+1

**Comment by JoshKeegan** [comment] 2016-05-18 16:08
@wa0x6e Sorry, I hadn't seen this when opening #201.

Having now read this, couldn't it be fixed with this CSS:
```
.cal-heatmap-container svg
{
    overflow: visible;
}
```
That shouldn't cause issues with domain navigation since .cal-heatmap-container still hides the overflow.

**Comment by wa0x6e** [comment] 2016-05-18 16:25
The issue is with `.cal-heatmap-container` itself. The container is clipping the border.

**Comment by JoshKeegan** [comment] 2016-05-18 16:34
For me, the problem isn't just where the overflow is being hidden by .cal-heatmap-container. 
If it was just caused by the container, then it wouldn't hide the overflow between two domains, but it is doing:
![dashboard - social sense - mozilla firefox_3](https://cloud.githubusercontent.com/assets/1682204/15366807/026f97d8-1d1e-11e6-9bfa-ca3a36c77d4c.jpg)

With my above snippet of CSS, the border displays correctly there.

So maybe there are other cases where it's the container, but in my usage it appears to have been the inner SVGs.

If there are cases where it's the container causing  the issue, perhaps we could still set the overflow to visible on the container by default and then toggle it before & after animations?

**Comment by wa0x6e** [comment] 2016-05-18 16:41
Toggling the CSS property seems a viable solution

**Comment by glutanimate** [comment] 2018-10-30 21:44
Still seeing the same issue here, unfortunately. As @JoshKeegan mentioned it seems to be happening both for outer and inner rects:

![screenshot_20181030_223848](https://user-images.githubusercontent.com/5459332/47752372-92257900-dc94-11e8-9765-1eeeacd854e3.png)

The workaround in #118 seems to work for some outer rects but not for other outer rects, and not for any of the affected inner rects.

Another weird thing is that for me this seems to be limited to Chromium on macOS (or rather the Chromium-based Qt WebEngine on macOS).

@wa0x6e Is there any CSS property I can adjust to fix the inner rect clipping? I've tried playing around with stroke width, etc., but to no avail.

Has anyone else managed to find a workaround in the meantime by any chance? Would really appreciate any and all help with this.

**Comment by dokgu** [comment] 2019-06-01 18:44
Having this problem as well. I used

```css
.cal-heatmap-container,
.cal-heatmap-container svg {
	overflow: visible !important;
}
```

and it seems to be fixed but I'm not sure if this would cause any issues. I'm at the very beginning of implementing this library.

**Closed** 2023-02-22 16:03 UTC
Labels: bug
